errors:
  flag: E
  type: exact
  value: -999
negatives:
  flag: 'N'
  type: range
  end:
    value: 0
    exclusive: true
repeats:
  flag: R
  type: repeats
  groupBy: ['coordinates.latitude', 'coordinates.longitude']
  orderBy: 'date.utc'
